// TODO: add support for disk/fat12/file_io drivers in the kernel
#include <stdarg.h>
#include "shared\base_types.h"
#include "shared\basic_defines.h"
#include "shared\vga\vga.h"
// #include "shared\bios\disk.h"
// #include "shared\disk\disk.h"
#include "shared\cpu\io.h"
#include "shared\cpu\timing.h"
#include "shared\math\integers.h"
#include "shared\strings\print.h"
// #include "shared\fat12\fat12.h"
#include "shared\memory\arena_allocator.h"
#include "shared\strings\path_handling.h"
#include "shared\memory\arena_allocator.h"
// #include "shared\file_io\file_io.h"
#include "shared\cpu\gdt.h"
#include "shared\cpu\idt.h"

#include "shared\vga\vga.c"
#include "shared\cpu\timing.c"
#include "shared\memory\memory.c"
#include "shared\strings\strings.c"
#include "shared\strings\print.c"
// #include "shared\disk\disk.c"
#include "shared\memory\arena_allocator.c"
#include "shared\strings\path_handling.c"
#include "shared\cpu\gdt.c"
#include "shared\cpu\idt.c"
// #include "shared\fat12\get.c"
// #include "shared\fat12\set.c"
// #include "shared\file_io\file_io.c"