// TODO: add support for disk/fat12/file_io drivers in the kernel
#include <stdarg.h>
#include "libraries\i686-elf\base_types.h"
#include "libraries\i686-elf\basic_defines.h"
#include "libraries\i686-elf\vga\vga.h"
// #include "libraries\i686-elf\bios\disk.h"
// #include "libraries\i686-elf\disk\disk.h"
#include "libraries\i686-elf\cpu\io.h"
#include "libraries\i686-elf\cpu\timing.h"
#include "libraries\i686-elf\math\integers.h"
#include "libraries\i686-elf\strings\print.h"
// #include "libraries\i686-elf\fat12\fat12.h"
#include "libraries\i686-elf\memory\arena_allocator.h"
#include "libraries\i686-elf\strings\path_handling.h"
#include "libraries\i686-elf\memory\arena_allocator.h"
// #include "libraries\i686-elf\file_io\file_io.h"
#include "libraries\i686-elf\cpu\gdt.h"
#include "libraries\i686-elf\cpu\idt.h"

#include "libraries\i686-elf\vga\vga.c"
#include "libraries\i686-elf\cpu\timing.c"
#include "libraries\i686-elf\memory\memory.c"
#include "libraries\i686-elf\strings\strings.c"
#include "libraries\i686-elf\strings\print.c"
// #include "libraries\i686-elf\disk\disk.c"
#include "libraries\i686-elf\memory\arena_allocator.c"
#include "libraries\i686-elf\strings\path_handling.c"
#include "libraries\i686-elf\cpu\gdt.c"
#include "libraries\i686-elf\cpu\idt.c"
// #include "libraries\i686-elf\fat12\get.c"
// #include "libraries\i686-elf\fat12\set.c"
// #include "libraries\i686-elf\file_io\file_io.c"